server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: Tweetle API Gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: GET, POST, PUT, DELETE
            allowedHeaders: Content-Type, Authorization
            maxAge: 3600
      routes:
        - id: TWEET-SERVICE
          uri: lb://TWEETLE-TWEET-SERVICE
          predicates:
            - Path=/api/tweets/**
        - id: USER-SERVICE
          uri: lb://TWEETLE-USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: SEARCH-SERVICE
          uri: lb://TWEETLE-SEARCH-SERVICE
          predicates:
            - Path=/api/search/**
        - id: TIMELINE-SERVICE
          uri: lb://TWEETLE-TIMELINE-SERVICE
          predicates:
            - Path=/api/timeline/**
        - id: TIMELINE-SERVICE
          uri: lb://TWEETLE-FOLLOWING-SERVICE
          predicates:
            - Path=/api/following/**
springdoc:
  swagger-ui:
    urls:
      - name: Tweet Service
        url: /api/tweets/v3/api-docs
      - name: User Service
        url: /api/users/v3/api-docs
      - name: Search Service
        url: /api/search/v3/api-docs
      - name: Timeline Service
        url: /api/timeline/v3/api-docs
      - name: Following Service
        url: /api/following/v3/api-docs